version: '2.1'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
  web:
    build: .
    image: web
    command: bundle exec rails s -p 3001 -b '0.0.0.0'
    volumes:
      - .:/user-ms
    ports:
      - "3001:3001"
    depends_on:
      - db
